name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.13", "pypy3.10"]
        exclude:
          - os: ubuntu-latest
            python-version: "3.11"
